# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

# Only for Snow CLI, can override connection details as follows
#export SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD=""

[default]
account = "tr28614.us-east4.gcp"
user = "SAHILK77"
password = "Bulbul@123"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "RAW_POS"

[connections.tr28614.us-east4.gcp]
account = "tr28614.us-east4.gcp"
user = "SAHILK77"
password = "Bulbul@123"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "RAW_POS"



